name: xml_utils
description: Simple utilities for managing XMLfiles
version: 0.1.0
homepage: https://github.com/giorgiofran/xml_utils

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  xml: ^6.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
